### ISSUE TITLE
Frontend - Add Signout Functionality.

### ISSUE THREAD

**Issue by muringitech** [mwangimuringi/zurihomes#102]
The frontend currently lacks the ability for users to sign out. Implement a function to handle user signout, including calling the backend API, clearing local storage, and redirecting users to the login page.
Acceptance Criteria:

    A handleSignout function should be created to send a request to the signout API.
    The authToken should be removed from local storage.
    The user should be redirected to the login page upon successful signout.

Tasks:

Add the handleSignout function to the appropriate component.
Update the navigation bar with a "Sign Out" button that calls the function.
Test the signout flow to ensure tokens are cleared and redirection works correctly.

**Comment by muringitech** [comment]
How do we handle state management post-signout?
If using Redux or Context API, dispatch an action to reset the user state after signout.

**Comment by mwangimuringi** [comment]
What happens if the signout API fails?
Display an appropriate error message to the user and ensure sensitive data is still cleared from local storage.
