### ISSUE TITLE
Middleware - Ensure Token Validation Doesn't Block Signout Route.

### ISSUE THREAD

**Issue by mwangimuringi** [mwangimuringi/zurihomes#103]
Currently, the authentication middleware may block access to all routes if the token is invalid or missing. The POST /api/users/signout endpoint should bypass this middleware to allow users to sign out even if they are not authenticated.
Acceptance Criteria:

    The authentication middleware should skip the /api/users/signout route.
    Users should be able to access the signout endpoint regardless of their authentication status.
    Ensure other secured routes remain protected.

Tasks:

Update the authentication middleware to exclude the /api/users/signout route.
Test the signout functionality to confirm it works without an active token.
Verify that other protected routes are unaffected.

**Comment by muringitech** [comment]
Why exclude the signout route from authentication middleware?
Users should be able to sign out even if their token is expired or invalid to clear the session or cookie on the client side.

**Comment by mwangimuringi** [comment]
How to confirm the middleware exclusion works?
Simulate a signout request with and without a valid token and verify the behavior is consistent.
