### ISSUE TITLE
Error during sign-up: JSON.parse: unexpected end of data at line 1 column 1.

### ISSUE THREAD

**Issue by mwangimuringi** [mwangimuringi/zurihomes#257]
**Description**
When attempting to sign up on ZuriHomes, the following error message is displayed:
`JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

**Steps to Reproduce**
1. Navigate to the ZuriHomes sign-up page.
2. Fill in the required fields with valid information.
3. Click on the "Sign Up" button.
4. Observe the error message displayed.

**Expected Behavior**
Successful account creation without any errors.

**Actual Behavior**
The sign-up process fails with the mentioned JSON parsing error.

**Additional Information**
- The issue occurs consistently across different browsers and devices.
- No network errors are observed in the browser's developer console.
- The backend API endpoint `/api/auth/signup` is suspected to return an empty or malformed JSON response.

![image](https://github.com/user-attachments/assets/6bded176-7449-430b-b154-c3355cf8e846)

**Environment**
- Operating System: [ Windows 10]
- Browser: [Firefox 84]
- Frontend Framework: [e React 17]
- Backend Framework: [Express.js 4]

**Comment by muringitech** [comment]
Ensure that the backend API endpoint `/api/auth/signup` returns a valid JSON response in all scenarios, including error cases. Implement error handling to manage unexpected responses gracefully on the frontend.
