### ISSUE TITLE
Error Display on API Failure

### ISSUE THREAD

**Issue by mwangimuringi** [mwangimuringi/zurihomes#31]
In the SignUp component, if an error occurs during the API call (such as a network failure or server-side error), the catch block handles it by displaying the error message. However, the loading state is only set to false after the catch block execution, which may create an inconsistent user experience by briefly leaving the loading state active even when an error occurs. This could confuse users by indicating that the request is still in progress while showing an error message.

**Comment by muringitech** [comment]
To ensure a consistent user experience, update the loading state as soon as an error is detected in the catch block. Here’s an example of how to modify the handleSubmit function to immediately set loading to false in case of an error:


const handleSubmit = async (e) => {
  e.preventDefault();
  try {
    setLoading(true);
    const res = await fetch("/api/auth/signup", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(formData),
    });
    const data = await res.json();

    if (data.success === false) {
      setError(data.message);
      setLoading(false);
      return;
    }

    setError(null);
    setLoading(false);
    navigate("/sign-in");

  } catch (error) {
    setLoading(false); // Ensure loading is reset
    setError(error.message);
  }
};

**Comment by mwangimuringi** [comment]
Great it worked.
