### ISSUE TITLE
Create Header Component and Make Profile Page Private

### ISSUE THREAD

**Issue by muringitech** [mwangimuringi/zurihomes#45]
1. Header Component

Design and implement a responsive header component in ReactJS, styled with TailwindCSS.
Add navigation links such as Home, Profile, and Logout.

    Use conditional rendering to show Login for unauthenticated users and Profile/Logout for authenticated users.

2. Private Profile Page

Create a private route component to restrict access to the profile page.
Implement backend authentication with Node.js and Express to verify users before granting profile access.
Add middleware to check user authentication on profile-related API routes.
Update frontend routing to redirect unauthenticated users to the login page when they attempt to access the profile page.

**Comment by mwangimuringi** [comment]
> 1. Header Component
> 
> 
> Design and implement a responsive header component in ReactJS, styled with TailwindCSS. Add navigation links such as Home, Profile, and Logout.
> 
> ```
> Use conditional rendering to show Login for unauthenticated users and Profile/Logout for authenticated users.
> ```
> 
>     2. Private Profile Page
> 
> 
> Create a private route component to restrict access to the profile page. Implement backend authentication with Node.js and Express to verify users before granting profile access. Add middleware to check user authentication on profile-related API routes. Update frontend routing to redirect unauthenticated users to the login page when they attempt to access the profile page.

    Ensure token-based session management and verification for consistent user experience.
    Maintain the current project folder structure and coding standards.
    Add documentation for any new components or functions.

**Comment by mwangimuringi** [comment]
This setup will improve navigation and privacy within the app.
