### ISSUE TITLE
Authorization Check Missing:

### ISSUE THREAD

**Issue by mwangimuringi** [mwangimuringi/zurihomes#69]
No middleware to confirm that the user attempting the update has the required permissions. Anyone knowing the id could potentially modify another user's data.

The route should allow only the authenticated user or admin to update profile details.

**Comment by muringitech** [comment]
Trigger the /update/:id endpoint with a valid user ID and incorrect authorization header.
Observe the behavior when data is submitted without validation.

**Comment by mwangimuringi** [comment]
its ok
